# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fbf15d2b2aac8efe1fdedece9227de32"
application_url = "https://adtest-production.up.railway.app"
embedded = true
name = "Adlign"
handle = "adlign"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "adlign.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_checkouts,read_customers,read_files,read_inventory,read_locations,read_metaobjects,read_metaobject_definitions,read_orders,read_product_listings,read_products,read_shipping,read_themes,write_files,write_metaobjects,write_metaobject_definitions,write_products,write_themes"

[auth]
redirect_urls = [ "https://adtest-production.up.railway.app/oauth/callback" ]

[pos]
embedded = false
